# Template for the config.yml file
# This file is used to store the configuration for the application

server:
  port: 3000

database:
  dbname: govtechdb_dev
  dbuser: root
  dbpassword: secret
  port: 5432

testdatabase:
  testdbname: govtechdb_test
  testdbuser: root
  testdbpassword: secret
  testport: 5432

environment: dev

